---
# tasks file for php_role
 - name: update apt
   apt: 
     name: '*'
     state: latest
 - name: to install php
   apt: 
     name: php
     state: present
 - name: install php-fpm
   apt: name=php8.3-fpm state=present
 - name: start php-fpm
   service: 
      name: php8.3-fpm
      state: started
