- name: lempservers
  hosts: localhost
  become: true
  connection: local
  tasks:
     - name: to stop apache
       service:
         name: apache2
         state: stopped
     - name: to install nginx
       apt: 
         name: nginx
         state: present
     - name: to start nginx
       service:
           name: nginx
           state: started
       notify: to restart nginx

     - name: to install php
       apt:
         name: php
         state: present
     - name: to install php-fpm
       apt:
          name: php8.3-fpm
          state: present
     - name: to start php
       service:
            name: php8.3-fpm
            state: started
       notify: to restart php

     - name: to install mariadb
       apt:
          name: mariadb-server
          state: present
     - name: to start maria-db
       service:
           name: mariadb
           state: started
       notify: to restart mariadb

  handlers: 
     - name: to restart nginx
       service: 
         name: nginx
         state: restarted
     - name: to restart php
       service:
         name: php8.3-fpm
         state: restarted
     - name: to restart mariadb
       service: 
         name: mariadb
         state: restarted
