- name: myplaybook
  hosts: webserver
  become: true
  connection: local
  tasks:
    - name: install LEMP
      apt:
       name: "{{ item }}"
       state: present
      loop:
        - nginx
        - php
        - php8.3-fpm
        - mariadb-server
    - name: start all service
      service: 
          name: "{{ item  }}"
          state: started
      loop: 
        - nginx
        - php8.3-fpm
        - mariadb
    - name: restart all service
      service: 
          name: "{{ item }}"
          state: restarted
      loop:
         - nginx
         - php8.3-fpm
         - mariadb
